### ISSUE TITLE
**Design Weather Change Event Protocol**

### ISSUE THREAD

**Issue by andrewkandzuba** [andrewkandzuba/green-garden-iot#1]
- [x] define weather change event structure
- [x] define temperature change event structure
- [x] define humidity change event structure
- [x] define wind's speed change event structure

**Comment by balamuru** [comment]
See https://dzone.com/articles/iotinternet-of-things-using-apache-camel-jboss-a-m for simple example

**Comment by andrewkandzuba** [comment]
I saw in the past that STOMP became very popular for IoT. By default Spring WebSockets component uses STOMP as base protocol under its hood.

**Comment by andrewkandzuba** [comment]
There are two options to define events for PubSub (or any similar exchange protocols):

- https://github.com/joelittlejohn/jsonschema2pojo - I've extensively used it in the past. Good and lightweight. The minus is that it does not support schema compatibility check.
- https://avro.apache.org/docs/current/spec.html - Apache Avro is more complicated however it is de-facto an industrial standard. Minus it is required additional cost for schema registry.
